volumes:
  mongo-data:
    external: true

services:
  gatherings:
    build:
      context: ./gatherings
      dockerfile: Dockerfile.dev
    ports:
      - 8000:8000
    volumes:
      - ./gatherings:/app
    environment:
      DATABASE_URL: mongodb://gather:gather@mongo/gather
      #added DATABASE_NAME and WAIT_HOSTS via Learn
      # DATABASE_NAME: gather
      # WAIT_HOSTS: mongo:27017
      MONGOHOST: mongo
      MONGODATABASE: gather
      MONGOUSER: gather
      MONGOPASSWORD: gather
  accounts:
    build:
      context: ./accounts
      dockerfile: Dockerfile.dev
    ports:
      - 8001:8000
    volumes:
      - ./accounts:/app
    environment:
      DATABASE_URL: mongodb://gather:gather@mongo/gather
      #added DATABASE_NAME and WAIT_HOSTS via Learn
      # DATABASE_NAME: gather
      # WAIT_HOSTS: mongo:27017
      MONGOHOST: mongo
      MONGODATABASE: gather
      MONGOUSER: gather
      MONGOPASSWORD: gather
  mongo:
    image: mongo:5
    volumes:
      - mongo-data:/data/db
      - ./data:/docker-entrypoint-initdb.d
      #- transfer:/transfer:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: gather
      MONGO_INITDB_ROOT_PASSWORD: gather
  mongo-express:
    image: mongo-express:0.54
    depends_on:
      - mongo
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: gather
      ME_CONFIG_MONGODB_ADMINPASSWORD: gather
      ME_CONFIG_MONGO_URL: mongodb://gather:gather@mongo:27017/
    restart: always

  ghi:
    image: node:lts-bullseye
    command: /bin/bash run.sh
    working_dir: /app
    volumes:
      - ./ghi:/app
    ports:
      - "3000:3000"
    environment:
      HOST_OS: ${OS}
      NODE_ENV: development
      HOST: "0.0.0.0"
      PUBLIC_URL: http://localhost:3000
      REACT_APP_GATHERINGS: http://localhost:8000
      REACT_APP_ACCOUNTS: http://localhost:8001
