export const blockList = [
    "American Samoa",
    "Baker Island",
    "Guam",
    "Howland Island",
    "Jarvis Island",
    "Johnston Atoll",
    "Kingman Reef",
    "Midway Atoll",
    "Navassa Island",
    "Northern Mariana Islands",
    "Palmyra Atoll",
    "Puerto Rico",
    "United States Minor Outlying Islands",
    "United States Virgin Islands",
    "Wake Island",
];
