export const reverseCuisines = {
  newamerican: "American (New)",
  tradamerican: "American (Traditional)",
  bbq: "Barbeque",
  breakfast_brunch: "Breakfast & Brunch",
  chinese: "Chinese",
  french: "French",
  german: "German",
  greek: "Greek",
  indpak: "Indian",
  italian: "Italian",
  japanese: "Japanese",
  korean: "Korean",
  mediterranean: "Mediterranean",
  mexican: "Mexican",
  pizza: "Pizza",
  sandwiches: "Sandwiches",
  spanish: "Spanish",
  thai: "Thai",
  vegetarian: "Vegetarian",
  vietnamese: "Vietnamese",
};
